package database

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	"github.com/jackc/pgx/v5"
	"github.com/opencardsonline/oco-web/config"
	logger "github.com/opencardsonline/oco-web/logging"
)

var migrationTableName = "migration_history"

func RunMigrations() {
	appConfig := config.AppConfig{}
	appConfig.LoadEnvVars()

	db := InitializeDBConnection(appConfig.DBConnectionString)

	mStruct := &MigrationStruct{}
	mStruct.New(db)

	mStruct.InitializeMigrationHistoryTable()
	migrationFiles := mStruct.getAllMigrationFiles()
	migrationsInDB := mStruct.getMigrationsInDB()
	migrationsToRun := mStruct.compareMigrationsToRun(migrationFiles, migrationsInDB)
	mStruct.performMigrations(migrationsToRun)
}

type MigrationStruct struct {
	db *pgx.Conn
}

func (_m *MigrationStruct) New(dbRef *pgx.Conn) {
	_m.db = dbRef
}

func (_m *MigrationStruct) InitializeMigrationHistoryTable() {
	sql := fmt.Sprintf(`
		CREATE TABLE IF NOT EXISTS "%s" (
		"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		"created_at" timestamp DEFAULT (now()),
		"filename" text
		);
	`, migrationTableName)
	_, err := _m.db.Exec(context.Background(), sql)
	if err != nil {
		logger.Log.Error("an error occurred when attempting to create the migration history table", "MigrationStruct.InitializeMigrationHistoryTable", err)
		os.Exit(1)
	}

}

type MigrationFile struct {
	Filename string
	SQL      string
}

func (_m *MigrationStruct) getAllMigrationFiles() []MigrationFile {
	migrationsDir := "./migrations"

	files, err := os.ReadDir(migrationsDir)
	if err != nil {
		logger.Log.Error("failed to read migrations directory", "MigrationStruct.getAllMigrationFiles", err)
		os.Exit(1)
	}

	var migrationFiles []MigrationFile

	for _, file := range files {
		if filepath.Ext(file.Name()) == ".sql" {
			filePath := filepath.Join(migrationsDir, file.Name())

			content, err := os.ReadFile(filePath)
			if err != nil {
				logger.Log.Error(fmt.Sprintf("failed to read migration file [%s]", filePath), "MigrationStruct.getAllMigrationFiles", err)
				continue
			}

			migrationFiles = append(migrationFiles, *(&MigrationFile{
				Filename: file.Name(),
				SQL:      string(content),
			}))
		}
	}

	return migrationFiles
}

func (_m *MigrationStruct) getMigrationsInDB() []string {

	sql := fmt.Sprintf(`
		SELECT filename 
			FROM public.%s
		ORDER BY created_at ASC 
	`, migrationTableName)
	rows, err := _m.db.Query(context.Background(), sql)
	if err != nil {
		logger.Log.Error("unable to read migrations from db", "MigrationStruct.getMigrationsInDB", err)
		os.Exit(1)
	}

	var filenames []string

	for rows.Next() {
		var value string
		if err := rows.Scan(&value); err != nil {
			logger.Log.Error("unable to read rows from migrations table", "MigrationStruct.getMigrationsInDB", err)
			os.Exit(1)
		}
		filenames = append(filenames, value)
	}

	return filenames
}

func (_m *MigrationStruct) compareMigrationsToRun(migrationFiles []MigrationFile, migrationsInDB []string) []MigrationFile {
	var filesToRun []MigrationFile

	contains := func(arr []string, value string) bool {
		for _, v := range arr {
			if v == value {
				return true
			}
		}
		return false
	}

	for _, migration := range migrationFiles {
		if !contains(migrationsInDB, migration.Filename) {
			filesToRun = append(filesToRun, migration)
		}
	}

	return filesToRun
}

func (_m *MigrationStruct) performMigrations(migrations []MigrationFile) {

	if len(migrations) > 0 {
		for _, migration := range migrations {

			logger.Log.Info("New Migration: " + migration.Filename)
			logger.Log.Info(migration.SQL)

			_, err := _m.db.Exec(context.Background(), migration.SQL)
			if err != nil {
				logger.Log.Error("an error occurred when attempting to execute the migration file", "MigrationStruct.performMigrations", err)
			} else {
				sql := fmt.Sprintf(`
					INSERT INTO public.%s (
						filename
					) 
					VALUES ($1)
			`, migrationTableName)
				_, err = _m.db.Exec(context.Background(), sql, migration.Filename)
				if err != nil {
					logger.Log.Error("an error occurred when attempting to write the logs to the migration history table", "MigrationStruct.performMigrations", err)
					os.Exit(1)
				}
			}
		}

		logger.Log.Info("Migrations Completed!")
	} else {
		logger.Log.Info("No new migrations to run!")
	}
}
